### ISSUE TITLE
[UX/DX] Design system migration

### ISSUE THREAD

**Issue by foxbunny** [indico/indico#5967]
This is a placeholder issue to track the progress of DS migration. We enumerate known items that need to be migrated to the DS. This migration will be done in parallel with accessibility work, focusing on public pages first.

- [ ] Merge the DS (open PR #5914)
- [ ] Search page tabs
- [ ] Search-related checkbox (update PR #5953)
- [ ] Search box/bar
- [ ] Category display headings (update PR #5944)
- [ ] Search result display
- [ ] Global menu (update PR #5897)
- [ ] Category navigator (update PR #5931)
- [ ] Category list
- [ ] Event list
