### ISSUE TITLE
Preserve translations when moving things from jinja to react...

### ISSUE THREAD

**Issue by AjobK** [indico/indico#6508]
**Is your feature request related to a problem? Please describe.**
All current context provided in issue
https://github.com/indico/indico/pull/6489#issuecomment-2307068700

**Describe the solution you'd like**
A mechanism to automatically parse translation files and put them in other formats so that we do not lose translations.

The issue is fairly complex and therefore needs refinement by @tomasr8 . Made the issue already for administrative purposes.

**Update 25/10**
This feature will be implemented on the CLI transifex (TBD) push command:
1. Untranslated POT files are generated by babel
2. Translated PO files are pulled
3. Check which translations are missing each environment (Jinja, React, JS) that another environment can supplement (We will have to think about double translations)
4. Push to transfixes translation for empty string in environment based on another environments translation
5. Pull PO files again, which now should all be in sync with duplicates

**Sub-issues for now**
- [ ] Get missing translations that are translated in other PO files (@AjobK )
- [ ] Push bunch of translations at once to Transifex (@micsucmed )

**Concerns for later**
- [ ] Formatted strings, how to deal with those
- [ ] Doubly translated strings, which to pick for empty message string
- [ ] Implementing this feature as a whole into the Indico CLI

**Comment by ThiefMaster** [comment]
How likely is it that the string matches *exactly* what we had in Jinja before? So I'm not sure how useful that'll be in the end...

**Comment by ThiefMaster** [comment]
One nice approach would be to make this a script in `bin/maintenance/...` that takes a git commit hash (the usual pot file update commit) and then check if any strings got moved w/o changes.

Then dump that as a first step, and afterwards see if Transifex has an API we can use to move those translations.

**Comment by tomasr8** [comment]
There is an [API](https://transifex.github.io/openapi/index.html#tag/Resource-Translations/paths/~1resource_translations/patch) for bulk updating translations, though for new strings we'd also first need to [create the resource string](https://transifex.github.io/openapi/index.html#tag/Resource-Strings/paths/~1resource_strings/post). Alternatively, maybe we could modify the PO files locally and use `tx push` instead

**Comment by ThiefMaster** [comment]
So the workflow that I usually use when updating pot files is:

- extract
- commit
- push to tx
- push to github

So I'd imagine running the script before/after the last step.

`tx push` has one big disadvantage: it pushes everything, and usually the local translations are not up to date (and I'd prefer to not have to update them just to update source strings... unless the script worked in a temporary directory and do a fresh pull first)

**Comment by tomasr8** [comment]
Yeah I think a fresh pull to temp directory would be the way to go. If we stick with the tx client we don't need to worry about transforming the data for the API and we already have a lot of utils for working with PO files. With the PO files it's also easy to compare the diff before pushing

**Comment by micsucmed** [comment]
Adding this flowchart of the current translation workflow for reference:
![indico_translations](https://github.com/user-attachments/assets/871af1a9-74fe-48ba-bc10-dd748ef4cdfc)

**Comment by tomasr8** [comment]
Looks correct, though the compilation step (`indico i18n compile`) which turns the .po files into .mo files (for python, for js we create a json I think) is missing. It should come after pulling the files from transifex.

**Comment by AjobK** [comment]
For future reference; discussion on keeping separate .POT files stored in repo:

https://github.com/indico/indico/pull/6606#discussion_r1834622024
