### ISSUE TITLE
Timetable export with Weasyprint

### ISSUE THREAD

**Issue by AjobK** [indico/indico#6554]
**Context**

Currently we use a sub-optimal library for exporting PDFs for the timetable. @tomasr8 has a PoC of the transition to a weasyprint-based approach.

**Task**

- [ ] Check integrity of all features (Everything still there)
- [ ] Re-evaluate which features are necessary (Ask for usage stats)
- [ ] Test refactored features
- [ ] Extend if necessary

**Branches**

Original branch: https://github.com/tomasr8/indico/tree/pdf-timetable

**Comment by tomasr8** [comment]
Original issue here: https://github.com/indico/indico/issues/6135

And here are some other issues which I found that are related to the timetable (not saying we should implement them, but since we're changing the library anyway it might be worth to have a look):

- https://github.com/indico/indico/issues/4083
- https://github.com/indico/indico/issues/1285 (This one's quite old, not sure if it's still relevant)

**Comment by AjobK** [comment]
# Checklist for functionalities and if they work properly.

**ADVANCED**
- [ ] Include cover page
- [ ] Include table of contents
- [ ] Show list of sessions in the table of contents
- [ ] Contributions related info
- [ ] Print the ID of each contribution
- [ ] Print abstract content of all contributions
- [ ] Include length of the contributions
- [ ] Sessions related info
- [ ] Print each session on a separate page
- [ ] Use session color codes
- [ ] Include session description
- [ ] Print the start date close to session title
- [ ] Breaks and contributions
- [ ] Include top-level contributions
- [ ] Include top-level breaks

**MISC**
- [ ] Show speaker title
- [ ] Show speaker affiliation

**Comment by AjobK** [comment]
Printing the ID for each contribution is not made and currently there is dummy data being used:

![Screenshot from 2024-09-23 10-12-58](https://github.com/user-attachments/assets/5eaa1169-2bea-4405-b54a-88b676236985)

**Comment by AjobK** [comment]
Stats for features. I agree with @tomasr8 that we should maybe get rid of the 'startpage' feature.

![Screenshot from 2024-09-23 10-20-20](https://github.com/user-attachments/assets/57629364-25fb-4fba-957f-004798065137)

**Comment by AjobK** [comment]
**Update** 

The design is fully updated for the cover page, ToC and session blocks. We also removed the following features due to their low popularity:

- Showing contribution ID (The ID adds no context)
- Changing the start page number (almost always 1)
- Session color codes (The usage of these colors has changed and we always want the session colors)

The following needs to still be done:

- [ ] :tada: Poster features
- [ ] :tada: Poster abstract features
- [ ] :wrench: Fixing the page count in the ToC
- [ ] :wrench: Getting the top-level contribution block colors (Using dummy color now)
- [ ] :test_tube: Test print to see if colors are problematic
- [ ] :soap: General code clean-up (including todo comments etc. and making some things more DRY)

**Comment by AjobK** [comment]
As discussed with @ThiefMaster , I am quite stuck for multiple days on a timeline CSS issue.

The timeline on the left of the session blocks displays unexpected behavior with long session blocks. Essentially, even though the session block breaks over multiple PDF pages (the full div), the timeline itself gets cut off on its page and does not continue onto the next page.

Even stranger is that on the next page, the div behaves as if the timeline is not there at all (takes full width of page). Will provide screenshot.

**Status**
| Date | State |
|- | - |
| 11/10/2024 | Lots of trial and error again, many lines written and deleted. Currently making a minimized mock-up to reproduce the problem and share it in the weasyprint and styling community. Probably stack overflow |

**Comment by AjobK** [comment]
Below you will find an exact (minimal) example of what I described in the comment below.

[broken_example.pdf](https://github.com/user-attachments/files/17344225/broken_example.pdf)


> ⚠️ As discussed with @ThiefMaster , I am quite stuck for multiple days on a timeline CSS issue. ⚠️
> 
> The timeline on the left of the session blocks displays unexpected behavior with long session blocks. Essentially, even though the session block breaks over multiple PDF pages (the full div), the timeline itself gets cut off on its page and does not continue onto the next page.
> 
> Even stranger is that on the next page, the div behaves as if the timeline is not there at all (takes full width of page). Will provide screenshot.
> 
> **Status**
> Date 	State
> 11/10/2024 	Lots of trial and error again, many lines written and deleted. Currently making a minimized mock-up to reproduce the problem and share it in the weasyprint and styling community. Probably stack overflow. Meanwhile looking for other tasks to take up, so that I can come back to this one 'fresh' and hopefully with answers.

**Comment by AjobK** [comment]
Confirmed with @tomasr8 that this is likely a bug. Asked question in Weasyprint issue: https://github.com/Kozea/WeasyPrint/issues/2274

**Comment by AjobK** [comment]
Due to poor efficiency for large events, it might be interesting to look into a C-based library at some point. This is however not in the scope for now and needs to be researched.

**Comment by ThiefMaster** [comment]
I don't think this is feasible, unless there is a library like weasyprint (same functionality) that's written in C (or Rust) AND has the same quality of Python bindings. Also, doesn't Weasyprint already use C-based libraries under the hood for various things?

Anyway, considering that this is not something which is done very frequently, I'd rather do what we talked about last week, ie offloading the PDF generation to a Celery task and polling for it to finish when the event is above a certain size.

**Comment by AjobK** [comment]
> I don't think this is feasible, unless there is a library like weasyprint (same functionality) that's written in C (or Rust) AND has the same quality of Python bindings. Also, doesn't Weasyprint already use C-based libraries under the hood for various things?
> 
> Anyway, considering that this is not something which is done very frequently, I'd rather do what we talked about last week, ie offloading the PDF generation to a Celery task and polling for it to finish when the event is above a certain size.

That's fine. I did not look under the hood of weasyprint yet, but we can stick to the celery-based approach.

**Comment by liZe** [comment]
Hi!

Sorry to get into your discussion. I’m Guillaume from CourtBouillon, WeasyPrint maintainers, and I may have some answers. :smile:

> I don't think this is feasible, unless there is a library like weasyprint (same functionality) that's written in C (or Rust) AND has the same quality of Python bindings.

There are other open source solutions, based on browsers’ engines, such as PagedJS or Vivliostyle, but they’re JS-based. Other well-known solutions are proprietary.

> Also, doesn't Weasyprint already use C-based libraries under the hood for various things?

WeasyPrint uses Pango and some of its dependencies to handle text. Most of the rest if pure Python or in the standard Python library.

WeasyPrint is known to be "slow", but there are solutions to [make it faster](https://doc.courtbouillon.org/weasyprint/stable/common_use_cases.html#improve-rendering-speed-and-memory-use).

Don’t hesitate to get in touch if you have more questions about this topic, templating for print, or anything else!

**Comment by AjobK** [comment]
Hey @liZe !

Thanks for commenting and providing some tips. For now we will stick with WeasyPrint and I'll look into the link on common use cases that you provided.

Cheers!
