### ISSUE TITLE
Creation of invoice/ticket/bills....from registrant list

### ISSUE THREAD

**Issue by jbenito3** [indico/indico#751]
``` yaml
# Ticket imported from Trac
```

**Comment by meluru** [comment]
It would be also nice to implement automatic payment notifications with receipt for all participants

**Comment by pferreir** [comment]
An example template from a real event:
![image](https://user-images.githubusercontent.com/2699/38919109-f0dbf742-42ef-11e8-9246-142d9df3b82f.png)

**Comment by vgvassilev** [comment]
Hi,

Today I have a few minutes to hack this together. I cannot attach tex files for some reason but I have them in my repo: https://github.com/vgvassilev/chep_docs/tree/master/payment_receipt

The idea is simple. We have a template and we have a `param.tex` file which contains a few variables. You can compile with `pdflatex receipt_template.tex`.

I have one question: is there some xml/json file that contains "all" registration data (including information about payments) if I am an event manager? This would make the generation of receipts for us almost automatic.

**Comment by ThiefMaster** [comment]
> I have one question: is there some xml/json file that contains "all" registration data (including information about payments) if I am an event manager? This would make the generation of receipts for us almost automatic.

You can export to CSV/XML after enabling all columns. We only export the columns that are displayed in the table.

**Comment by vgvassilev** [comment]
I am afraid that would not suffice, we are lacking information such as the "extra fees" if the person paid by credit card. People want to get reimbursed not for the X euros conference fee but X + Y, where Y is the overall transactions fees (if they paid by card or were charged for any other reason).

**Comment by pferreir** [comment]
I'm not sure whether we want to do this with TeX or instead Reportlab. Generating and compiling TeX is fine for stuff that has to look like TeX (e.g. abstracts) but not so convenient for the rest.

**Comment by vgvassilev** [comment]
Either way, feel free to use it/not use it ;)

I will solve my problem if I can get access to xml containing people's payment details.

**Comment by pferreir** [comment]
Interesting find: https://react-pdf.org/
Having a (sandboxed?) micro-service which replaces the current ReportLab-based PDF generation code would help a lot with this. We could even allow templates to be produced in JSX.

**Comment by pferreir** [comment]
# Some mockups
## Template management
![image](https://user-images.githubusercontent.com/2699/135239827-6acef2c2-b2ff-4a73-b9e3-762c1e850cbb.png)
![image](https://user-images.githubusercontent.com/2699/135240174-31a9d3ef-bdea-4918-bf77-0d63c916b973.png)
## Adding a new template
![image](https://user-images.githubusercontent.com/2699/135240375-6c057afd-5d26-4394-a832-9d7d0453fc0d.png)
## List of Registrants
![image](https://user-images.githubusercontent.com/2699/135240458-ca1854ff-8800-4180-9c30-09687ae505dd.png)
## Registrant Details
![image](https://user-images.githubusercontent.com/2699/135240574-984c2652-551f-4186-b977-8c8aea64a7f8.png)
## "Generate" dialog
![image](https://user-images.githubusercontent.com/2699/135240642-8e007161-196c-4168-8555-90604b7f14b3.png)

**Comment by vgvassilev** [comment]
Nice!! Thanks a lot for working on this!

**Comment by pferreir** [comment]
## Tasks

* Create base module/models (`indico.modules.events.receipts`):
   - [ ] Base module (w/ empty files)
   - [ ] `ReceiptTemplate` model - pay attention to handling of custom fields
   - [ ] `Receipt` model - once again, pay close attention to handling of custom fields
 * Create template management interface
   - [ ] Add new template
   - [ ] Edit a template
   - [ ] Remove a template
 * [ ] Add endpoint to generate a receipt/certificate for a given registrant, based on a given template and custom fields
 * [ ] Add section in registrant details which includes generated receipts/certificates
 * Add "Generate Receipt" option to list of registrants;
   - [ ] Add "Generate" dialog
   - [ ] Add backend action: download PDF or ZIP file
   - [ ] Add backend action: publish in user's registrant details (visible by them, and optionally e-mail file as well)
   - [ ] Add backend action: e-mail file to user(s)
 * [ ] Create default templates
 * [ ] Unit tests
 * [ ] Document feature in learn.getindico.io

**Comment by pferreir** [comment]
Some additional suggestions by @plourenco, @javfg and @ThiefMaster (mostly stuff for the late stages of development):
 * [ ] list of available "placeholders" or variables which are available in the template
 * [ ] adding some sort of highlighting to the text areas ([react-monacoeditor](https://github.com/jaywcjlove/react-monacoeditor))?

**Comment by javfg** [comment]
Just adding a reminder to notify the Claims Office when this is finished, as they are interested in the feature.

**Comment by barachwal** [comment]
Hello! @ThiefMaster. Currently release version is `v3.2.8`  is there any chance to know estimate of  the `v3.3` release date? :) Of course I'm asking from this `invoice` module proposal perspective :)

**Comment by ThiefMaster** [comment]
The module is nearly finished (just pending a review and some testing) and I guess we'll deploy v3.3 to production at CERN in December. Once we consider it stable enough there's nothing in the way of a proper public release.

**Comment by pferreir** [comment]
Guess we can close this?
